# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://www.pantsbuild.org/stable/docs/using-pants/using-pants-in-ci for tips on how to set up your CI with Pants.

name: Pants

on: [push, workflow_dispatch]

jobs:
  build:
    name: Perform CI Checks
    strategy:
      matrix:
        runner:
          # Replace with your profile label https://namespace.so/docs/features/faster-github-actions#using-runner-profiles
          - namespace-profile-default
          - namespace-profile-default-arm64
        python-version: [3.9]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up remote cache
      run: |
        nsc pants cache setup --pants-toml=/tmp/pants.toml
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pantsbuild/actions/init-pants@v8
      # This action bootstraps pants and manages 2-3 GHA caches.
      # See: github.com/pantsbuild/actions/tree/main/init-pants/
      with:
        gha-cache-key: v0
        named-caches-hash: ${{ hashFiles('python-default.lock') }}
        pants-ci-config: "['pants.toml', '/tmp/pants.toml']"

    - name: Check BUILD files
      run: |
        pants tailor --check update-build-files --check ::
    - name: Lint and typecheck
      run: |
        pants lint check ::
    - name: Test
      run: |
        pants test ::
    - name: Package / Run
      run: |
        # We also smoke test that our release process will work by running `package`.
        pants package ::
        pants run helloworld/:pex_binary
    - name: Upload pants log
      uses: namespace-actions/upload-artifact@v1
      with:
        name: pants-log-${{ matrix.runner }}
        path: .pants.d/workdir/pants.log
      if: always()  # We want the log even on failures.
